MODE: "training"

DATASET:
  LOCATION: "./data/era5_conus_2025_1_to_2025_12_6var.zarr"
  PREPROCESSING:
    SP: 
    - 0to1
    T2M: 
    - z-scale
    TCC: []
    TP: 
    - m-to-mm
    - logp1
    U10: 
    - -1to1
    V10: 
    - -1to1

MODEL:
  ARCHITECTURE: "ConvGRU"
  INPUT_DIMS: 6
  HIDDEN_DIM: 20
  KERNEL_SIZE: 5
  NUM_LAYERS: 2
  NUM_PRED_STEPS: 3

TRAINING:
  EPOCHS: 30
  OPTIMIZER: "AdamW"
  LEARNING_RATE: 0.0001
  LOSS: "LocalLoss"
  TEST_NAME: "test_run"

INFERENCE:
  MODEL_WEIGHTS: "src/weights/test_run/test_run.pth"
  DATASET: "test"
